;;; packages.el -*- lexical-binding: t; -*-
(package! rainbow-delimiters)
(package! buffer-terminator)
(package! nerd-icons-ibuffer)
(package! catppuccin-theme)
(package! rainbow-mode)
(package! org-roam-ui)
(package! org-super-agenda)
(package! consult-org-roam)
(package! laas)
(package! org-fragtog)
(package! yasnippet-snippets)
(package! magit-todos)
(package! git-gutter)
(package! embark-vc)
(package! sudo-edit)
(package! feature-mode)
(package! evil-textobj-tree-sitter)
(package! dired-open)
(package! dired-ranger)
(package! lsp-latex)
(package! jinx)
(package! org-remark)
(package! nix-mode)
(package! nix-ts-mode)

;;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━
;;; Unpinned Packages
;;; ━━━━━━━━━━━━━━━━━━━━━━━━━━━
(unpin! consult)
(unpin! consult-dir)
(unpin! embark)
(unpin! embark-consult)
(unpin! corfu)
(unpin! nerd-icons-corfu)
;; (unpin! nerd-icons-completion)
;; (unpin! wgrep)
(unpin! corfu-terminal)
;; (unpin! orderless)
(unpin! cape)
(unpin! marginalia)
(unpin! vertico)
(unpin! yasnippet)
(unpin! yasnippet-capf)
(unpin! consult-yasnippet)
(unpin! citar)
(unpin! citar-embark)
(unpin! citar-org-roam)
(unpin! parsebib)
(unpin! citeproc)
(unpin! apheleia)
;; (unpin! yasnippet)
;; (unpin! doom-snippets)
(unpin! nerd-icons)
;; (unpin! dirvish)
