#!/bin/bash
# SSH Hardening Script - Based on CIS Benchmarks and Modern Security Standards
# Exit on error, undefined variables, and pipe failures
set -euo pipefail

# Script configuration
readonly SCRIPT_NAME="$(basename "$0")"
readonly SSH_CONFIG_DIR="/etc/ssh/sshd_config.d"
readonly SSH_CONFIG_FILE="${SSH_CONFIG_DIR}/99-hardening.conf"
readonly BACKUP_DIR="/root/ssh_backup_$(date +%Y%m%d_%H%M%S)"

# Color codes for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Logging function
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*"
}

error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

# Error handling
cleanup() {
    local exit_code=$?
    if [[ ${exit_code} -ne 0 ]]; then
        error "Script failed with exit code ${exit_code}"
        error "Backup configuration available at: ${BACKUP_DIR}"
    fi
}

trap cleanup EXIT

# Check if running as root
if [[ ${EUID} -ne 0 ]]; then
    error "This script must be run as root"
    exit 1
fi

log "Starting SSH hardening configuration..."

# Create backup directory
log "Creating backup directory: ${BACKUP_DIR}"
mkdir -p "${BACKUP_DIR}"

# Backup existing SSH configuration
log "Backing up existing SSH configuration..."
if [[ -f /etc/ssh/sshd_config ]]; then
    cp -p /etc/ssh/sshd_config "${BACKUP_DIR}/sshd_config.backup"
fi
if [[ -d ${SSH_CONFIG_DIR} ]]; then
    cp -pr "${SSH_CONFIG_DIR}" "${BACKUP_DIR}/"
fi

# Create SSH config directory if it doesn't exist
if [[ ! -d ${SSH_CONFIG_DIR} ]]; then
    log "Creating SSH config directory: ${SSH_CONFIG_DIR}"
    mkdir -p "${SSH_CONFIG_DIR}"
fi

# Create hardened SSH configuration
log "Creating hardened SSH configuration at ${SSH_CONFIG_FILE}"
cat >"${SSH_CONFIG_FILE}" <<'EOF'
# SSH Hardening Configuration
# Generated by SSH hardening script
# Based on CIS Benchmarks and modern security standards

# Network and Port Configuration
Port 47
AddressFamily inet

# Logging - VERBOSE logs key fingerprints for forensic analysis
LogLevel VERBOSE

# Authentication Settings
PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
PubkeyAuthentication yes

# Disable keyboard-interactive and challenge-response authentication
# Both settings ensure PAM cannot bypass password restrictions
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no

# PAM Configuration
UsePAM yes

# Disable Dangerous Features
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
PermitUserEnvironment no

# Host-based Authentication (Disable)
IgnoreRhosts yes
HostbasedAuthentication no

# Session Management and Timeouts
# ClientAliveInterval: Send keepalive every 300 seconds (5 min)
# ClientAliveCountMax: 0 = disconnect immediately after timeout
# Total timeout: 300 seconds of inactivity
ClientAliveInterval 300
ClientAliveCountMax 0
TCPKeepAlive no
LoginGraceTime 60

# Connection Limits
MaxAuthTries 3
MaxSessions 2
MaxStartups 10:30:60

# Modern Cryptographic Algorithms (Post-Quantum Ready)
# Key Exchange: Prioritize post-quantum sntrup761 and modern curve25519
KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256

# Ciphers: Use AEAD ciphers and strong AES
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# MACs: Encrypt-then-MAC (ETM) variants for better security
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# Host Key Algorithms: Prefer Ed25519, then RSA with SHA-2
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com

# Public Key Algorithms
PubkeyAcceptedAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com

# Optional: Uncomment to restrict SSH access to specific users/groups
# AllowUsers user1 user2
# AllowGroups sshusers

# Optional: Display warning banner
# Banner /etc/issue.net
EOF

# Set correct permissions
log "Setting correct permissions on SSH configuration files..."
chmod 600 "${SSH_CONFIG_FILE}"
chmod 600 /etc/ssh/sshd_config

# Test SSH configuration
log "Testing SSH configuration syntax..."
if sshd -t; then
    log "SSH configuration syntax is valid"
else
    error "SSH configuration syntax test failed!"
    error "Please check ${SSH_CONFIG_FILE} for errors"
    exit 1
fi

# Display effective configuration for verification
info "Testing effective SSH configuration for port 47..."
if sshd -T | grep -q "^port 47$"; then
    log "Port 47 configuration verified"
else
    warning "Port 47 not found in effective configuration"
fi

echo ""
log "SSH hardening configuration completed successfully!"
echo ""
warning "═══════════════════════════════════════════════════════════════"
warning "                    IMPORTANT NEXT STEPS"
warning "═══════════════════════════════════════════════════════════════"
echo ""
info "1. Backup saved to: ${BACKUP_DIR}"
echo ""
info "2. Before restarting SSH, ensure:"
echo "   - You have SSH public key in ~/.ssh/authorized_keys"
echo "   - The key has correct permissions (700 for ~/.ssh, 600 for authorized_keys)"
echo "   - Your firewall allows port 47 (run firewalld.sh script next)"
echo ""
info "3. After configuring firewall and testing port 47:"
echo "   sudo systemctl restart sshd"
echo ""
info "4. Test connection on new port from another terminal:"
echo "   ssh -p 47 user@server"
echo ""
warning "DO NOT restart SSH until firewall is configured!"
warning "═══════════════════════════════════════════════════════════════"
