#!/bin/bash
cd && git clone https://github.com/zefr0x/ianny.git
cd ianny
sudo meson setup builddir -Dbuildtype=release
sudo meson compile -C builddir
sudo meson install -C builddir
cd && sudo rm -rf ianny
