#!/bin/bash
sudo apt install --no-install-recommends pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber rtkit libspa-0.2-bluetooth gstreamer1.0-pipewire bluez gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav ffmpeg libavcodec-extra pavucontrol pamixer alsa-utils playerctl
