#!/bin/bash
sudo add-apt-repository ppa:avengemedia/danklinux
sudo apt update
sudo apt install --no-install-recommends cliphist quickshell-git
cd
mkdir -p ~/.config/quickshell/noctalia-shell && curl -sL https://github.com/noctalia-dev/noctalia-shell/releases/latest/download/noctalia-latest.tar.gz | tar -xz --strip-components=1 -C ~/.config/quickshell/noctalia-shell
cd
