#!/bin/bash
ln -sv "$HOME/Git/configs/linux-system/dots/bin/" "$HOME/"
ln -sv "$HOME/Git/configs/linux-system/dots/.zshrc" "$HOME/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/atuin/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/bat/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/btop/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/enchant/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/fd/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/gh/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/ghostty/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/home-manager/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/hypr/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/imv/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/lazygit/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/nvim/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/pipewire/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/swappy/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/tealdeer/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/tmux/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/xdg-desktop-portal/" "$HOME/.config"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/yazi/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/zathura/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/chrome-flags.conf" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/electron-flags.conf" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/mimeapps.list" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/starship.toml" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/user-dirs.dirs" "$HOME/.config/"

# Configure User
mkdir -p "$HOME/.npm-global"
npm config set prefix "$HOME/.npm-global"
