vim.keymap.set("n", "<leader>sv", "<C-w>v", { desc = "Split window vertically", silent = true })
vim.keymap.set("n", "<leader>sh", "<C-w>s", { desc = "Split window horizontally", silent = true })
vim.keymap.set("n", "<leader>se", "<C-w>=", { desc = "Equalize split sizes", silent = true })
vim.keymap.set("n", "<leader>sx", "<cmd>close<cr>", { desc = "Close current split", silent = true })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Go to left window", silent = true })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Go to lower window", silent = true })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Go to upper window", silent = true })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Go to right window", silent = true })
vim.keymap.set("n", "<A-j>", ":m .+1<cr>==", { desc = "Move line down", silent = true })
vim.keymap.set("n", "<A-k>", ":m .-2<cr>==", { desc = "Move line up", silent = true })
vim.keymap.set("v", "<A-j>", ":m '>+1<cr>gv=gv", { desc = "Move line down", silent = true })
vim.keymap.set("v", "<A-k>", ":m '<-2<cr>gv=gv", { desc = "Move line up", silent = true })
vim.keymap.set("i", "jk", "<Esc>", { desc = "Exit insert mode", silent = true })
vim.keymap.set("n", "<leader>nh", "<cmd>nohl<cr>", { desc = "Clear search highlight", silent = true })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left and keep selection", silent = true })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right and keep selection", silent = true })
vim.keymap.set("n", "<leader>L", "<cmd>Lazy<cr>", { desc = "Open Lazy UI", silent = true })
