vim.opt.number = true -- Show line numbers
vim.opt.relativenumber = true -- Show relative line numbers
vim.opt.signcolumn = "yes" -- Always show sign column
vim.opt.cursorline = true -- Highlight the current line
vim.opt.wrap = false -- Disable line wrapping
vim.opt.scrolloff = 8 -- Keep 8 lines above/below cursor
vim.opt.sidescrolloff = 8 -- Keep 8 columns left/right of cursor
vim.opt.tabstop = 2 -- Number of spaces a tab counts for
vim.opt.shiftwidth = 2 -- Spaces per indentation level
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.smartindent = true -- Smart auto-indentation
vim.opt.ignorecase = true -- Ignore case in search patterns
vim.opt.smartcase = true -- Override ignorecase if uppercase present
vim.opt.splitright = true -- Open vertical splits to the right
vim.opt.splitbelow = true -- Open horizontal splits below
vim.opt.termguicolors = true -- Enable 24-bit RGB color support
vim.opt.undofile = true -- Enable persistent undo history
vim.opt.undodir = vim.fn.stdpath("data") .. "/undo" -- Directory for undo files
vim.opt.clipboard = "unnamedplus" -- Sync clipboard with system
vim.opt.updatetime = 200 -- Faster completion and diagnostics refresh
vim.opt.timeoutlen = 300 -- Milliseconds to wait for mapped sequence
vim.opt.mouse = "a" -- Enable mouse support in all modes
vim.opt.completeopt = { "menu", "menuone", "noselect" } -- Completion menu behavior
vim.opt.pumheight = 10 -- Maximum height of popup menu
vim.opt.fileencoding = "utf-8" -- Default file encoding
vim.opt.conceallevel = 0 -- Do not conceal markup characters
vim.opt.showmode = false -- Hide mode display (noice.nvim handles it)
