#!/bin/bash
sudo cp -R "$HOME/Git/configs/linux-system/fedora/preconfig/dnf.conf" "/etc/dnf/"
sudo cp -R "$HOME/Git/configs/linux-system/tumbleweed/preconfig/99-custom-env.sh" "/etc/profile.d/"

sudo dnf install bleachbit bpftune brightnessctl btop cava mpv cronie curl ddcutil direnv distrobox podman emacs-pgtk fail2ban fd gnome-keyring gnome-tweaks gnuplot go grim slurp gsettings-desktop-schemas hunspell gzip haveged i2c-tools imv inotify-tools ispell jq logrotate luajit lynis papers papirus-icon-theme topgrade podman profile-sync-daemon pymol swappy trash-cli udiskie xdg-user-dirs xdg-user-dirs-gtk  zram-generator zsh bluez bluez-tools wget nautilus xdg-desktop-portal-gtk xdg-desktop-portal-hyprland wlsunset file-roller evolution-data-server nwg-look transmission-gtk hyprpolkitagent zathura zathura-pdf-mupdf qt6ct qt5ct switcheroo-control hyprland hyprland-devel pipx wl-clipboard tmux kitty cliphist

curl -LsSf https://astral.sh/uv/install.sh | sh
curl -fsSL https://pixi.sh/install.sh | sh
curl -fsSL https://bun.com/install | bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

pipx install pyprland

PIA_INSTALLER=$(mktemp --suffix=.run)
trap "rm -f '$PIA_INSTALLER'" EXIT
wget -O "$PIA_INSTALLER" https://installers.privateinternetaccess.com/download/pia-linux-3.6.2-08398.run
chmod +x "$PIA_INSTALLER"
bash "$PIA_INSTALLER"

ln -sv "$HOME/Git/configs/linux-system/dots/bin/" "$HOME/"
ln -sv "$HOME/Git/configs/linux-system/dots/.zshrc" "$HOME/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/atuin/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/bat/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/btop/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/enchant/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/fd/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/gh/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/ghostty/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/home-manager/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/hypr/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/imv/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/lazygit/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/nvim/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/pipewire/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/pypr/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/swappy/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/tealdeer/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/tmux/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/xdg-desktop-portal/" "$HOME/.config"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/yazi/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/zathura/" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/chrome-flags.conf" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/electron-flags.conf" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/mimeapps.list" "$HOME/.config/"
ln -sv "$HOME/Git/configs/linux-system/dots/.config/starship.toml" "$HOME/.config/"
sudo rm -rf ~/.config/user-dirs.dirs
ln -sv "$HOME/Git/configs/linux-system/dots/.config/user-dirs.dirs" "$HOME/.config/"

# Configure User
mkdir -p "$HOME/.npm-global"
npm config set prefix "$HOME/.npm-global"

systemctl enable --user app-com.mitchellh.ghostty.service
chsh -s $(which zsh)
