# NOTE: managed by uwsm
# exec-once = dbus-update-activation-environment --systemd --all
# exec-once = systemctl --user start hyprland-session.target
exec-once = udiskie 
# NOTE: mananged by cliphist.desktop
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpm reload -n
