exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = udiskie --notify
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpm reload -n
# exec-once = swww-daemon
# exec-once = sleep 3 && ~/.local/bin/noctalia-theme-sync
# exec-once = hypridle

