monitorv2 {
    output = HDMI-A-5
    mode = 2560x1440@60
    position = 0x0
    scale = 1.33
    bitdepth = 10
    cm = auto
    sdrbrightness = 1.0
    sdrsaturation = 1.0
    supports_hdr = true
    supports_wide_color = true
    sdr_min_luminance = 0.005
    sdr_max_luminance = 250
    min_luminance = 0
    max_luminance = 1000
    max_avg_luminance = 500
}

render {
    cm_fs_passthrough = 2
    cm_auto_hdr = 2
}

# monitorv2 {
#     output = eDP-1
#     mode = 2560x1440@60
#     position = 0x0
# scale = 1.33
# }

env = ENABLE_HDR_WSI, 1
monitor = eDP-1, disable
