# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# GENERAL
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

general {
    gaps_in = 4
    gaps_out = 7
    border_size = 3
    col.active_border = rgba(b8bb26ff) rgba(fabd2fff) 45deg
    col.inactive_border = rgba(3c3836cc) rgba(504945cc) 45deg
    layout = scroller
    resize_on_border = true

    snap {
        enabled = true
    }
}



# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DECORATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

decoration {
    rounding = 8
    rounding_power = 3
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1
    dim_inactive = false

    shadow {
        enabled = true
        range = 2
        render_power = 1
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
        ignore_opacity = true
        xray = false
        special = true
        vibrancy = 0.1696
        popups = true
    }
}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ANIMATIONS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

animations {
    enabled = true

    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1

    animation = windows, 1, 4, wind, popin
    animation = windowsIn, 1, 4, winIn, popin
    animation = windowsOut, 1, 4, winOut, popin
    animation = windowsMove, 1, 4, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, once
    animation = fade, 1, 4, default
    animation = workspaces, 1, 5, wind, slidevert
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# INPUT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

input {
    kb_layout = us
    kb_options = ctrl:nocaps
    follow_mouse = 1
    accel_profile = flat
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# LAYOUTS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

dwindle {
	preserve_split = true
	smart_split = true
	smart_resizing = true
}

master {
    new_status = master
}

scrolling {
    column_width             = 0.40
    follow_min_visible       = 0.33
    fullscreen_on_one_column = false
    focus_fit_method         = 1
    direction = right
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MISC
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

misc {
  vrr = 0
  disable_hyprland_logo = true
  force_default_wallpaper = 0
  middle_click_paste = false
  focus_on_activate = true
  session_lock_xray = true
  enable_swallow = true
  swallow_regex = ^(Alacritty|kitty|footclient)$
}

xwayland {
  force_zero_scaling = true
}

# debug {
#   watchdog_timeout = 0
# }
debug {
   disable_logs = false
   enable_stdout_logs = true
}
