# Workspace layout assignments
workspace = 1, layout:scrolling
workspace = 2, layout:scrolling
workspace = 3, layout:scrolling
workspace = 4, layout:hy3
workspace = 5, layout:hy3
workspace = 6, layout:hy3
workspace = 7, layout:master
workspace = 8, layout:master
workspace = 9, layout:monocle


# Named workspaces (for launcher and quick access)
workspace = name:research, layout:scroller
workspace = name:dev, layout:hy3
workspace = name:comm, layout:master
workspace = name:stage, layout:scroller   # for nsticky stage

# Switch Workspaces (Super+1-9)
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9

# Move Window to Workspace
bind = Super+Shift, 1, movetoworkspace, 1
bind = Super+Shift, 2, movetoworkspace, 2
bind = Super+Shift, 3, movetoworkspace, 3
bind = Super+Shift, 4, movetoworkspace, 4
bind = Super+Shift, 5, movetoworkspace, 5
bind = Super+Shift, 6, movetoworkspace, 6
bind = Super+Shift, 7, movetoworkspace, 7
bind = Super+Shift, 8, movetoworkspace, 8
bind = Super+Shift, 9, movetoworkspace, 9

# Relative switching
binde = Ctrl+Alt, down, workspace, +1
binde = Ctrl+Alt, up,  workspace, -1

bind = Super, bracketleft,        workspace, e-1
bind = Super, bracketright,       workspace, e+1
bind = Ctrl+Super+Alt, up,  movetoworkspace, -1
bind = Ctrl+Super+Alt, down, movetoworkspace, +1

# Named workspace bindings
# bind = Super, R, workspace, name:research
# bind = Super, D, workspace, name:dev
# bind = Super, C, workspace, name:comm
# bind = Super, H, workspace, name:stage
