color0 #131316
color1 #ffb4ab
color2 #c0c2f8
color3 #c5c4dc
color4 #efb5dd
color5 #c0c2f8
color6 #c5c4dc
color7 #e5e1e6
color8 #919099
color9 #ffb4ab
color10 #c0c2f8
color11 #c5c4dc
color12 #efb5dd
color13 #c0c2f8
color14 #c5c4dc
color15 #e5e1e6

cursor                #e5e1e6
cursor_text_color     #131316
background            #131316
foreground            #e5e1e6
selection_foreground  #c7c5d0
selection_background  #46464f
active_border_color   #c0c2f8
inactive_border_color #46464f
url_color             #c0c2f8
