color0 #212330
color1 #fd4663
color2 #8b91c1
color3 #b181af
color4 #ab82b0
color5 #acb0d3
color6 #d0afce
color7 #f2f2f3
color8 #636673
color9 #fd4663
color10 #8b91c1
color11 #b181af
color12 #ab82b0
color13 #acb0d3
color14 #d0afce
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1b23
background            #1a1b23
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #212330
active_border_color   #8b91c1
inactive_border_color #212330
url_color             #8b91c1

active_tab_foreground   #1b1c22
active_tab_background   #8b91c1
inactive_tab_foreground #afb0b6
inactive_tab_background #212330
cursor_trail_color      #afb0b6
