color0 #1c1d21
color1 #fd4663
color2 #989cb3
color3 #908da5
color4 #978fa3
color5 #b6b9c9
color6 #bab8c7
color7 #f2f2f3
color8 #666870
color9 #fd4663
color10 #989cb3
color11 #908da5
color12 #978fa3
color13 #b6b9c9
color14 #bab8c7
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c1d21
background            #1c1d21
foreground            #f2f2f3
selection_foreground  #b0b1b5
selection_background  #26262c
active_border_color   #989cb3
inactive_border_color #26262c
url_color             #989cb3

active_tab_foreground   #101013
active_tab_background   #989cb3
inactive_tab_foreground #b0b1b5
inactive_tab_background #26262c
cursor_trail_color      #b0b1b5
