COMMON_FLAGS="-O3 -march=raptorlake -pipe -flto -fno-plt -fno-semantic-interposition"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LDFLAGS}"
CGO_CFLAGS="${CFLAGS}"
CGO_CXXFLAGS="${CXXFLAGS}"
CGO_FFLAGS="${FFLAGS}"
CGO_LDFLAGS="${LDFLAGS}"
MAKEOPTS="-j22"
NOCOMMON_OVERRIDE_LIBTOOL="yes"
EMERGE_DEFAULT_OPTS="--jobs=10 --keep-going=y --ask"
#ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"
VIDEO_CARDS="nvidia"
USE="systemd -cups -elogind -fips -gnome -handbook gtk4 vdpau clang \
     -kde -motif -pulseaudio -quicktime -smartcard gtk tpm opengl \
     apparmor appindicator -bluetooth firmware lvm gstreamer nftables \
     gui keyring libnotify lto pgo jit nvenc nvidia pipewire -iptables \
     qt5 qt6 udisks upower wayland zstd X -ccache -accessibility \
     cryptsetup device-mapper audit policykit hardened vulkan llvm"
L10N="en"
LINGUAS="en"
ABI_X86="64"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# Secure Boot signing certificate and key (from sbctl)
SECUREBOOT_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
SECUREBOOT_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"
LC_MESSAGES=C
